spring.profiles.active: dev
---
spring:
  profiles: dev
debug: true
---
spring:
  profiles: prod
debug: false
---
feed.filename: demo.feed

# You can specify multiple profile specific YAML documents in a single file.